### ISSUE TITLE
Question: Is muffin still active?

### ISSUE THREAD

**Issue by marcosmoyano** [klen/muffin#57]
I see the latest commit is from Nov 13, 2017. 
Currently looking for a micro-framework to pick up. Ideally I'd like to pick one that is still active.

What's the status of muffin's development?

**Comment by klen** [comment]
Muffin is deprecated. I suggest finding another one.

**Comment by uSpike** [comment]
There's been a lot of activity lately.  Is this project still deprecated?

**Comment by klen** [comment]
The current version (0.45.3) is ASGI 3.0 compatible, `aiohttp` independent, supports both `Asyncio` and `Trio` libraries. Some of Muffin's plugins have been rewritten to support the latest version, some in work. Is it still deprecated? Since I didn't rewrite the README it is. But it's also a working framework with features that supports modern things.

The problem with the previous version was it was based on `aiohttp` stack. When the stack got powerful enough the Muffin becomes useless. Because the `aiohttp` is a web framework also. The new version doesn't depend on any framework it's an independent library.
